name: BreedHorse
version: '${version}'
main: one.tranic.breedhorse.BreedHorse
folia-supported: true
api-version: '1.17'
authors: [404Setup]
description: Let the horses breed better offspring under the effect of potion?
website: https://modrinth.com/user/404Setup