name: BreedHorse
version: '${version}'
main: one.tranic.breedhorse.BreedHorse
folia-supported: true
api-version: '1.17'
authors: [404Setup]
description: is MCPE-81890
website: https://modrinth.com/plugin/breedhorse
permissions:
  breedhorse.command.reload:
    default: op
  breedhorse.command.version:
    default: op
  breedhorse.update_message:
    default: op